[workspace]
members = [
    "walkers",
    "demo",
    "demo_native",
    "demo_web",
    "demo_android/rust",
    "hypermocker",
]
resolver = "2"

[workspace.package]
version = "0.41.0"
rust-version = "1.85" # Aligned to egui

[workspace.dependencies]
image = { version = "0.25", default-features = false }
log = "0.4"
egui = "0.31.1"
egui_extras = { version = "0.31.1", features = ["svg"] }
eframe = "0.31.1"
egui-winit = "0.31.1"


# TODO: remove this and bump egui to 0.32 when released
[patch.crates-io]
eframe = { git = "https://github.com/emilk/egui.git", branch = "main" }
egui = { git = "https://github.com/emilk/egui.git", branch = "main" }
egui_extras = { git = "https://github.com/emilk/egui.git", branch = "main" }
egui-winit = { git = "https://github.com/emilk/egui.git", branch = "main" }